//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UstamOdev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class adminler
    {
        public int admin_id { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Kullanýcý Adý")]
        public string admin_email { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Þifre")]
        [DataType(DataType.Password)]
        public string admin_sifre { get; set; }
    }
}
