//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UstamOdev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public musteriler()
        {
            this.onayli_isler = new HashSet<onayli_isler>();
        }

        public int musteri_id { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Ýsim Soyisim")]
        public string musteri_isim_soyisim { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "E-Posta")]
        [DataType(DataType.EmailAddress)]
        public string musteri_email { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Þifre")]
        [DataType(DataType.Password)]
        public string musteri_sifre { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Telefon")]
        [DataType(DataType.PhoneNumber)]
        public string musteri_tel { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Adres")]
        public string musteri_adres { get; set; }
        [Required(ErrorMessage = "Alan boþ geçilemez")]
        [Display(Name = "Ýl")]
        public string musteri_il { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onayli_isler> onayli_isler { get; set; }
    }
}
