//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UstamOdev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class onayli_isler
    {
        public int onay_id { get; set; }
        public int is_id { get; set; }
        public int musteri_id { get; set; }
        public string onay_durum { get; set; }
    
        public virtual is_ilanlari is_ilanlari { get; set; }
        public virtual musteriler musteriler { get; set; }
    }
}
